// Regenerates packages/chain/src/abis.ts from Foundry build artifacts.
// Usage (from the repository root, after `cd contracts && forge build`): pnpm chain:abis
import { readFileSync, writeFileSync } from "node:fs"

const root = new URL("../../../", import.meta.url)
const abiOf = (name) =>
  JSON.parse(readFileSync(new URL(`contracts/out/${name}.sol/${name}.json`, root), "utf8")).abi

const capability = abiOf("CapabilityRegistry")
const context = abiOf("ContextRegistry")
const batchAnchor = abiOf("BatchAnchor")
const source = `// GENERATED by packages/chain/scripts/gen-abis.mjs from contracts/out. Do not edit by hand.
// Regenerate with \`pnpm chain:abis\` after any contract change.
export const capabilityRegistryAbi = ${JSON.stringify(capability, null, 2)} as const

export const contextRegistryAbi = ${JSON.stringify(context, null, 2)} as const

export const batchAnchorAbi = ${JSON.stringify(batchAnchor, null, 2)} as const
`
writeFileSync(new URL("packages/chain/src/abis.ts", root), source)
console.log(`abis.ts <- CapabilityRegistry (${capability.length} items), ContextRegistry (${context.length} items), BatchAnchor (${batchAnchor.length} items)`)
