export const PROTOCOL_VERSION = "mida-protocol-v1" as const
export * from "./errors.js"
export * from "./constants.js"
export * from "./types.js"
export * from "./wire.js"
export * from "./namespaces.js"
export * from "./ids.js"
export * from "./typed-data.js"
export * from "./batch.js"
export * from "./webauthn-assertion.js"
export * from "./owner-link.js"
