// GENERATED by packages/chain/scripts/gen-abis.mjs from contracts/out. Do not edit by hand.
// Regenerate with `pnpm chain:abis` after any contract change.
export const capabilityRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "vaultRpId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "NAMESPACE_COUNT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "POLICY_HASH_V1",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "VAULT_RP_ID_HASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "activeCapabilityIds",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentEpoch",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentIdOfSigner",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochPublicKey",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgent",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AgentRegistry.AgentRecord",
        "components": [
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "signer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "encryptionPublicKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "encryptionKeyVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "callbackOriginHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "capabilityManifestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "capabilityManifestVersion",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCapability",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "capability",
        "type": "tuple",
        "internalType": "struct CapabilityStore.Capability",
        "components": [
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "namespaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "permissions",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "provenancePolicy",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "agentEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "grantedAtReadEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "revoked",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantBatch",
    "inputs": [
      {
        "name": "request",
        "type": "tuple",
        "internalType": "struct AccessRequestInput",
        "components": [
          {
            "name": "requestId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "nonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "agentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "purposeIdHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "callbackOriginHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestVersion",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "policyVersionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "namespaceTreeVersionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "requestExpiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "capabilityExpiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "scopes",
            "type": "tuple[]",
            "internalType": "struct GrantScope[]",
            "components": [
              {
                "name": "namespaceId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "permissions",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "provenancePolicy",
                "type": "uint8",
                "internalType": "uint8"
              }
            ]
          },
          {
            "name": "agentSignature",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "finalScopes",
        "type": "tuple[]",
        "internalType": "struct GrantScope[]",
        "components": [
          {
            "name": "namespaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "permissions",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "provenancePolicy",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "auth",
        "type": "tuple",
        "internalType": "struct WebAuthn.WebAuthnAuth",
        "components": [
          {
            "name": "authenticatorData",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "clientDataJSON",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "challengeIndex",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "typeIndex",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "r",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "s",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "capabilityIds",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "grantNonce",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasAuthority",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "permissions",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "provenanceBits",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initializeReadEpoch",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "publicKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isAuthorized",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "permission",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isCapabilityValid",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isHighSensitivity",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isRegisteredNamespace",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isWriteEpochValid",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "namespaceParent",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ownerP256Key",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "qx",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "qy",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "p256RotationNonce",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerAgent",
    "inputs": [
      {
        "name": "agentSalt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "encryptionPublicKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "callbackOriginHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "capabilityManifestHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signerSignature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registerP256Key",
    "inputs": [
      {
        "name": "qx",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "qy",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requiredReadEpoch",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "revoke",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeAgentAndRotate",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "rotations",
        "type": "tuple[]",
        "internalType": "struct Revocations.EpochRotation[]",
        "components": [
          {
            "name": "namespaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "newEpochPublicKey",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeAndRotate",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newEpochPublicKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rotateAgentEncryptionKey",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newEncryptionPublicKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rotateAgentSigner",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newSigner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "newSignerSignature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rotateExpiredEpoch",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newEpochPublicKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rotateP256Key",
    "inputs": [
      {
        "name": "newQx",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "newQy",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "auth",
        "type": "tuple",
        "internalType": "struct WebAuthn.WebAuthnAuth",
        "components": [
          {
            "name": "authenticatorData",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "clientDataJSON",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "challengeIndex",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "typeIndex",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "r",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "s",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAgentCallbackOrigin",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newCallbackOriginHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "signerRotationNonce",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "updateAgentCapabilityManifest",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "bodyHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "manifestVersion",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "operatorSignature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "vaultRpId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "writeDeadline",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AgentCapabilityManifestUpdated",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "capabilityManifestHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "capabilityManifestVersion",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentEncryptionKeyRotated",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "encryptionPublicKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "encryptionKeyVersion",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentOriginChanged",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "callbackOriginHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentRegistered",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "encryptionPublicKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "encryptionKeyVersion",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "callbackOriginHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "capabilityManifestHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "capabilityManifestVersion",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentRevoked",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "agentEpoch",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentSigningKeyRotated",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousSigner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newSigner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CapabilityGranted",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "capabilityId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "permissions",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "provenancePolicy",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "context",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct Grants.GrantContext",
        "components": [
          {
            "name": "requestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestVersion",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "policyVersionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "namespaceTreeVersionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "grantNonce",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CapabilityRevoked",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "agentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "capabilityId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NamespaceEpochKeySet",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "readEpoch",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "publicKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NamespaceRegistered",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "parentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "highSensitivity",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "P256KeyRegistered",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "qx",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "qy",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "rotationNonce",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReadEpochRequired",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "readEpoch",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "writeDeadline",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AgentAlreadyRegistered",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AgentNotFound",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AuthorityExceedsRequest",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CallbackOriginMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CapabilityAlreadyRevoked",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CapabilityLimit",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CapabilityNotFound",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyRpId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EpochAlreadyInitialized",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochNotExpired",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochRotationRequired",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExpiryInvalid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HighSensitivityExpiry",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidNamespace",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ManifestStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ManifestVersionInvalid",
    "inputs": [
      {
        "name": "expected",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "submitted",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotCapabilityOwner",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotOperator",
    "inputs": [
      {
        "name": "agentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "P256KeyExists",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "P256KeyMissing",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReadRequiresRotation",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RequestExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RotationNotApplicable",
    "inputs": [
      {
        "name": "capabilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RotationSetMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ScopesNotCanonical",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SignerAlreadyBound",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "VersionUnsupported",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WebAuthnInvalid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroEpochKey",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroP256Key",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroValue",
    "inputs": []
  }
] as const

export const contextRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "capabilityRegistry",
        "type": "address",
        "internalType": "contract ICapabilityRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CAPABILITY_REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICapabilityRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "exists",
    "inputs": [
      {
        "name": "contextId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRecord",
    "inputs": [
      {
        "name": "contextId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "record",
        "type": "tuple",
        "internalType": "struct ContextRegistry.ContextRecord",
        "components": [
          {
            "name": "contextId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "author",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "namespaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "lineageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "parentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ciphertextCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "readEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "version",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recordType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "lineagePolicy",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "provenanceSource",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latest",
    "inputs": [
      {
        "name": "lineageId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "register",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "inputs",
        "type": "tuple[]",
        "internalType": "struct ContextRegistry.ContextInput[]",
        "components": [
          {
            "name": "contextId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "objectNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "namespaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedParentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ciphertextCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "readEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "recordType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "lineagePolicy",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "provenanceSource",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "contextIds",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "ContextRegistered",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "contextId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "record",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct ContextRegistry.ContextRecord",
        "components": [
          {
            "name": "contextId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "author",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "namespaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "lineageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "parentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "manifestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ciphertextCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "readEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "version",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recordType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "lineagePolicy",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "provenanceSource",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ContextSuperseded",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "lineageId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "contextId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "parentId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "version",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EvidenceRegistered",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "namespaceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "contextId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "author",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "manifestHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AnchorOwnerOnly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CapabilityDenied",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ContextIdMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitted",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ContextNotFound",
    "inputs": [
      {
        "name": "contextId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "DuplicateContext",
    "inputs": [
      {
        "name": "contextId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyBatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EpochRotationRequired",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochStale",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitted",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "required",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "EvidenceImmutable",
    "inputs": [
      {
        "name": "parentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidNamespace",
    "inputs": [
      {
        "name": "namespaceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidRecord",
    "inputs": [
      {
        "name": "contextId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ParentMismatch",
    "inputs": [
      {
        "name": "parentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ProvenanceForbidden",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StaleParent",
    "inputs": [
      {
        "name": "expectedParentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "currentHead",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroRegistry",
    "inputs": []
  }
] as const
