/**
 * This file is generated by HyperIndex codegen from config.yaml and schema.graphql.
 * Do not edit manually.
 * If your project's types look out of date, run `envio codegen`
 * (or your package manager's `codegen` script, e.g. `pnpm codegen`).
 */

import type { Address, BigDecimal, SingleOrMultiple } from "envio";

/** Marks a block/transaction field that this event's `field_selection` doesn't include.
 * Reading such a field is a type error; the message tells you which field to add to
 * `field_selection` in config.yaml to make it available. */
type FieldNotSelected<Message extends string> = { readonly __fieldNotSelected: Message };

type EvmBlock = {
  /** The number field. */
  readonly number: number;
  /** The timestamp field. */
  readonly timestamp: number;
  /** The hash field. */
  readonly hash: string;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - parentHash
   * ```
   */
  readonly parentHash: FieldNotSelected<"Field 'parentHash' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - nonce
   * ```
   */
  readonly nonce: FieldNotSelected<"Field 'nonce' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - sha3Uncles
   * ```
   */
  readonly sha3Uncles: FieldNotSelected<"Field 'sha3Uncles' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - logsBloom
   * ```
   */
  readonly logsBloom: FieldNotSelected<"Field 'logsBloom' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - transactionsRoot
   * ```
   */
  readonly transactionsRoot: FieldNotSelected<"Field 'transactionsRoot' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - stateRoot
   * ```
   */
  readonly stateRoot: FieldNotSelected<"Field 'stateRoot' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - receiptsRoot
   * ```
   */
  readonly receiptsRoot: FieldNotSelected<"Field 'receiptsRoot' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - miner
   * ```
   */
  readonly miner: FieldNotSelected<"Field 'miner' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - difficulty
   * ```
   */
  readonly difficulty: FieldNotSelected<"Field 'difficulty' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - totalDifficulty
   * ```
   */
  readonly totalDifficulty: FieldNotSelected<"Field 'totalDifficulty' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - extraData
   * ```
   */
  readonly extraData: FieldNotSelected<"Field 'extraData' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - size
   * ```
   */
  readonly size: FieldNotSelected<"Field 'size' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - gasLimit
   * ```
   */
  readonly gasLimit: FieldNotSelected<"Field 'gasLimit' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - gasUsed
   * ```
   */
  readonly gasUsed: FieldNotSelected<"Field 'gasUsed' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - uncles
   * ```
   */
  readonly uncles: FieldNotSelected<"Field 'uncles' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - baseFeePerGas
   * ```
   */
  readonly baseFeePerGas: FieldNotSelected<"Field 'baseFeePerGas' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - blobGasUsed
   * ```
   */
  readonly blobGasUsed: FieldNotSelected<"Field 'blobGasUsed' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - excessBlobGas
   * ```
   */
  readonly excessBlobGas: FieldNotSelected<"Field 'excessBlobGas' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - parentBeaconBlockRoot
   * ```
   */
  readonly parentBeaconBlockRoot: FieldNotSelected<"Field 'parentBeaconBlockRoot' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - withdrawalsRoot
   * ```
   */
  readonly withdrawalsRoot: FieldNotSelected<"Field 'withdrawalsRoot' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - l1BlockNumber
   * ```
   */
  readonly l1BlockNumber: FieldNotSelected<"Field 'l1BlockNumber' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - sendCount
   * ```
   */
  readonly sendCount: FieldNotSelected<"Field 'sendCount' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - sendRoot
   * ```
   */
  readonly sendRoot: FieldNotSelected<"Field 'sendRoot' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       block_fields:
   *         - mixHash
   * ```
   */
  readonly mixHash: FieldNotSelected<"Field 'mixHash' is not selected for the '<EventName>' event. Add it under field_selection.block_fields in config.yaml.">;
};
type EvmTransaction = {
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - transactionIndex
   * ```
   */
  readonly transactionIndex: FieldNotSelected<"Field 'transactionIndex' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /** The hash field. */
  readonly hash: string;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - from
   * ```
   */
  readonly from: FieldNotSelected<"Field 'from' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - to
   * ```
   */
  readonly to: FieldNotSelected<"Field 'to' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - gas
   * ```
   */
  readonly gas: FieldNotSelected<"Field 'gas' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - gasPrice
   * ```
   */
  readonly gasPrice: FieldNotSelected<"Field 'gasPrice' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - maxPriorityFeePerGas
   * ```
   */
  readonly maxPriorityFeePerGas: FieldNotSelected<"Field 'maxPriorityFeePerGas' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - maxFeePerGas
   * ```
   */
  readonly maxFeePerGas: FieldNotSelected<"Field 'maxFeePerGas' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - cumulativeGasUsed
   * ```
   */
  readonly cumulativeGasUsed: FieldNotSelected<"Field 'cumulativeGasUsed' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - effectiveGasPrice
   * ```
   */
  readonly effectiveGasPrice: FieldNotSelected<"Field 'effectiveGasPrice' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - gasUsed
   * ```
   */
  readonly gasUsed: FieldNotSelected<"Field 'gasUsed' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - input
   * ```
   */
  readonly input: FieldNotSelected<"Field 'input' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - nonce
   * ```
   */
  readonly nonce: FieldNotSelected<"Field 'nonce' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - value
   * ```
   */
  readonly value: FieldNotSelected<"Field 'value' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - v
   * ```
   */
  readonly v: FieldNotSelected<"Field 'v' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - r
   * ```
   */
  readonly r: FieldNotSelected<"Field 'r' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - s
   * ```
   */
  readonly s: FieldNotSelected<"Field 's' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - contractAddress
   * ```
   */
  readonly contractAddress: FieldNotSelected<"Field 'contractAddress' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - logsBloom
   * ```
   */
  readonly logsBloom: FieldNotSelected<"Field 'logsBloom' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - root
   * ```
   */
  readonly root: FieldNotSelected<"Field 'root' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - status
   * ```
   */
  readonly status: FieldNotSelected<"Field 'status' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - yParity
   * ```
   */
  readonly yParity: FieldNotSelected<"Field 'yParity' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - accessList
   * ```
   */
  readonly accessList: FieldNotSelected<"Field 'accessList' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - maxFeePerBlobGas
   * ```
   */
  readonly maxFeePerBlobGas: FieldNotSelected<"Field 'maxFeePerBlobGas' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - blobVersionedHashes
   * ```
   */
  readonly blobVersionedHashes: FieldNotSelected<"Field 'blobVersionedHashes' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - type
   * ```
   */
  readonly type: FieldNotSelected<"Field 'type' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - l1Fee
   * ```
   */
  readonly l1Fee: FieldNotSelected<"Field 'l1Fee' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - l1GasPrice
   * ```
   */
  readonly l1GasPrice: FieldNotSelected<"Field 'l1GasPrice' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - l1GasUsed
   * ```
   */
  readonly l1GasUsed: FieldNotSelected<"Field 'l1GasUsed' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - l1FeeScalar
   * ```
   */
  readonly l1FeeScalar: FieldNotSelected<"Field 'l1FeeScalar' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - gasUsedForL1
   * ```
   */
  readonly gasUsedForL1: FieldNotSelected<"Field 'gasUsedForL1' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
  /**
   * @deprecated Not selected for this event. To enable, add to config.yaml:
   * ```yaml
   * events:
   *   - event: <EventName>
   *     field_selection:
   *       transaction_fields:
   *         - authorizationList
   * ```
   */
  readonly authorizationList: FieldNotSelected<"Field 'authorizationList' is not selected for the '<EventName>' event. Add it under field_selection.transaction_fields in config.yaml.">;
};
declare namespace FuelTypes {}
type Enums = {};
type Entities = {
  "Agent": {
    readonly "id": string;
    readonly "operator": string;
    readonly "signer": string;
    readonly "registeredBlock": number;
    readonly "revokedByOwners": number;
    readonly "manifestVersion": bigint;
    readonly "isOutsideOperator": boolean;
    readonly "encryptionKeyVersion": number | undefined;
    readonly "callbackOriginHash": string | undefined;
  };
  "AgentGrantBook": {
    readonly "id": string;
    readonly "activeCapabilityIds": readonly string[];
  };
  "ContextRecord": {
    readonly "id": string;
    readonly "owner": string;
    readonly "namespaceId": string;
    readonly "author": string;
    readonly "lineageId": string;
    readonly "parentId": string;
    readonly "recordType": number;
    readonly "kind": number;
    readonly "version": number;
    readonly "readEpoch": bigint;
    readonly "createdAt": bigint;
    readonly "expiresAt": bigint;
    readonly "supersededBy": string | undefined;
    readonly "supersededBlock": number | undefined;
    readonly "registeredBlock": number;
    readonly "txHash": string;
  };
  "GlobalStats": {
    readonly "id": string;
    readonly "owners": number;
    readonly "agents": number;
    readonly "operators": number;
    readonly "agentsByOutsideOperators": number;
    readonly "grants": number;
    readonly "activeGrants": number;
    readonly "capabilityRevocations": number;
    readonly "agentRevocations": number;
    readonly "contextRecords": number;
    readonly "supersessions": number;
    readonly "evidenceRecords": number;
    readonly "lastBlock": number;
    readonly "lastTimestamp": bigint;
  };
  "Grant": {
    readonly "id": string;
    readonly "owner": string;
    readonly "agent": string;
    readonly "namespaceId": string;
    readonly "permissions": number;
    readonly "provenancePolicy": number;
    readonly "expiresAt": bigint;
    readonly "grantedBlock": number;
    readonly "revokedBlock": number | undefined;
    readonly "revokedBy": string | undefined;
    readonly "txHash": string;
  };
  "Namespace": {
    readonly "id": string;
    readonly "parentId": string;
    readonly "name": string;
    readonly "highSensitivity": boolean;
    readonly "registeredBlock": number;
  };
  "Operator": {
    readonly "id": string;
    readonly "agentsRegistered": number;
    readonly "firstSeenBlock": number;
  };
  "Owner": {
    readonly "id": string;
    readonly "firstSeenBlock": number;
    readonly "grants": number;
    readonly "revocations": number;
    readonly "records": number;
    readonly "p256Registered": boolean;
  };
  "ProcessedEvent": {
    readonly "id": string;
  };
  "Revocation": {
    readonly "id": string;
    readonly "owner": string;
    readonly "kind": string;
    readonly "agentId": string;
    readonly "namespaceId": string | undefined;
    readonly "capabilityId": string | undefined;
    readonly "block": number;
    readonly "timestamp": bigint;
    readonly "txHash": string;
  };
  "TimelineEntry": {
    readonly "id": string;
    readonly "owner": string;
    readonly "kind": string;
    readonly "block": number;
    readonly "logIndex": number;
    readonly "timestamp": bigint;
    readonly "txHash": string;
    readonly "agentId": string | undefined;
    readonly "namespaceId": string | undefined;
    readonly "capabilityId": string | undefined;
    readonly "contextId": string | undefined;
  };
};

declare module "envio" {
  interface Global {
    config: {
      evm: { chains: {
  "monadTestnet": { id: 10143 };
      }; contracts: {
  "CapabilityRegistry": {
    "AgentRegistered": {
      /** The name of the event. */
      readonly eventName: "AgentRegistered";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly agentId: string; readonly operator: Address; readonly signer: Address; readonly encryptionPublicKey: string; readonly encryptionKeyVersion: bigint; readonly callbackOriginHash: string; readonly capabilityManifestHash: string; readonly capabilityManifestVersion: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "AgentRevoked": {
      /** The name of the event. */
      readonly eventName: "AgentRevoked";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly agentId: string; readonly agentEpoch: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "AgentCapabilityManifestUpdated": {
      /** The name of the event. */
      readonly eventName: "AgentCapabilityManifestUpdated";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly agentId: string; readonly capabilityManifestHash: string; readonly capabilityManifestVersion: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "AgentEncryptionKeyRotated": {
      /** The name of the event. */
      readonly eventName: "AgentEncryptionKeyRotated";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly agentId: string; readonly encryptionPublicKey: string; readonly encryptionKeyVersion: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "AgentOriginChanged": {
      /** The name of the event. */
      readonly eventName: "AgentOriginChanged";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly agentId: string; readonly callbackOriginHash: string };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "AgentSigningKeyRotated": {
      /** The name of the event. */
      readonly eventName: "AgentSigningKeyRotated";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly agentId: string; readonly previousSigner: Address; readonly newSigner: Address };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "CapabilityGranted": {
      /** The name of the event. */
      readonly eventName: "CapabilityGranted";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly agentId: string; readonly namespaceId: string; readonly capabilityId: string; readonly permissions: bigint; readonly provenancePolicy: bigint; readonly expiresAt: bigint; readonly context: { readonly requestHash: string; readonly manifestHash: string; readonly manifestVersion: bigint; readonly policyVersionHash: string; readonly namespaceTreeVersionHash: string; readonly grantNonce: bigint } };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "CapabilityRevoked": {
      /** The name of the event. */
      readonly eventName: "CapabilityRevoked";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly agentId: string; readonly namespaceId: string; readonly capabilityId: string };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "NamespaceRegistered": {
      /** The name of the event. */
      readonly eventName: "NamespaceRegistered";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly namespaceId: string; readonly parentId: string; readonly name: string; readonly highSensitivity: boolean };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "NamespaceEpochKeySet": {
      /** The name of the event. */
      readonly eventName: "NamespaceEpochKeySet";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly namespaceId: string; readonly readEpoch: bigint; readonly publicKey: string };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "P256KeyRegistered": {
      /** The name of the event. */
      readonly eventName: "P256KeyRegistered";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly qx: bigint; readonly qy: bigint; readonly rotationNonce: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "ReadEpochRequired": {
      /** The name of the event. */
      readonly eventName: "ReadEpochRequired";
      /** The name of the contract that emitted this event. */
      readonly contractName: "CapabilityRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly namespaceId: string; readonly readEpoch: bigint; readonly writeDeadline: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
  };
  "ContextRegistry": {
    "ContextRegistered": {
      /** The name of the event. */
      readonly eventName: "ContextRegistered";
      /** The name of the contract that emitted this event. */
      readonly contractName: "ContextRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly namespaceId: string; readonly contextId: string; readonly record: { readonly contextId: string; readonly owner: Address; readonly author: string; readonly namespaceId: string; readonly lineageId: string; readonly parentId: string; readonly manifestHash: string; readonly ciphertextCommitment: string; readonly evidenceCommitment: string; readonly readEpoch: bigint; readonly createdAt: bigint; readonly expiresAt: bigint; readonly version: bigint; readonly recordType: bigint; readonly lineagePolicy: bigint; readonly kind: bigint; readonly provenanceSource: bigint } };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "ContextSuperseded": {
      /** The name of the event. */
      readonly eventName: "ContextSuperseded";
      /** The name of the contract that emitted this event. */
      readonly contractName: "ContextRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly lineageId: string; readonly contextId: string; readonly parentId: string; readonly version: bigint };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
    "EvidenceRegistered": {
      /** The name of the event. */
      readonly eventName: "EvidenceRegistered";
      /** The name of the contract that emitted this event. */
      readonly contractName: "ContextRegistry";
      /** The unique identifier of the blockchain network where this event occurred. */
      readonly chainId: 10143;
      /** The parameters or arguments associated with this event. */
      readonly params: { readonly owner: Address; readonly namespaceId: string; readonly contextId: string; readonly author: string; readonly manifestHash: string };
      /** The block in which this event was recorded. Configurable via `field_selection` in config.yaml. */
      readonly block: EvmBlock;
      /** The transaction that triggered this event. Configurable via `field_selection` in config.yaml. */
      readonly transaction: EvmTransaction;
      /** The index of this event's log within the block. */
      readonly logIndex: number;
      /** The address of the contract that emitted this event. */
      readonly srcAddress: Address;
    };
  };
      }; eventFilters: {
  "CapabilityRegistry": {
    "AgentRegistered": { readonly params: { readonly agentId?: SingleOrMultiple<string>; readonly operator?: SingleOrMultiple<Address>; readonly signer?: SingleOrMultiple<Address> } };
    "AgentRevoked": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly agentId?: SingleOrMultiple<string> } };
    "AgentCapabilityManifestUpdated": { readonly params: { readonly agentId?: SingleOrMultiple<string> } };
    "AgentEncryptionKeyRotated": { readonly params: { readonly agentId?: SingleOrMultiple<string> } };
    "AgentOriginChanged": { readonly params: { readonly agentId?: SingleOrMultiple<string> } };
    "AgentSigningKeyRotated": { readonly params: { readonly agentId?: SingleOrMultiple<string>; readonly previousSigner?: SingleOrMultiple<Address>; readonly newSigner?: SingleOrMultiple<Address> } };
    "CapabilityGranted": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly agentId?: SingleOrMultiple<string>; readonly namespaceId?: SingleOrMultiple<string> } };
    "CapabilityRevoked": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly agentId?: SingleOrMultiple<string>; readonly namespaceId?: SingleOrMultiple<string> } };
    "NamespaceRegistered": { readonly params: { readonly namespaceId?: SingleOrMultiple<string>; readonly parentId?: SingleOrMultiple<string> } };
    "NamespaceEpochKeySet": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly namespaceId?: SingleOrMultiple<string>; readonly readEpoch?: SingleOrMultiple<bigint> } };
    "P256KeyRegistered": { readonly params: { readonly owner?: SingleOrMultiple<Address> } };
    "ReadEpochRequired": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly namespaceId?: SingleOrMultiple<string> } };
  };
  "ContextRegistry": {
    "ContextRegistered": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly namespaceId?: SingleOrMultiple<string>; readonly contextId?: SingleOrMultiple<string> } };
    "ContextSuperseded": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly lineageId?: SingleOrMultiple<string>; readonly contextId?: SingleOrMultiple<string> } };
    "EvidenceRegistered": { readonly params: { readonly owner?: SingleOrMultiple<Address>; readonly namespaceId?: SingleOrMultiple<string>; readonly contextId?: SingleOrMultiple<string> } };
  };
      } };
      entities: Entities;
      perChainEntities: never;
      enums: Enums;
    };
  }

  export type Agent = Entities["Agent"];
  export type AgentGrantBook = Entities["AgentGrantBook"];
  export type ContextRecord = Entities["ContextRecord"];
  export type GlobalStats = Entities["GlobalStats"];
  export type Grant = Entities["Grant"];
  export type Namespace = Entities["Namespace"];
  export type Operator = Entities["Operator"];
  export type Owner = Entities["Owner"];
  export type ProcessedEvent = Entities["ProcessedEvent"];
  export type Revocation = Entities["Revocation"];
  export type TimelineEntry = Entities["TimelineEntry"];
}
